//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOcrApp.appdata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class data3000Entities : DbContext
    {
        public data3000Entities()
            : base("name=data3000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Corrections> Corrections { get; set; }
        public virtual DbSet<Folyo> Folyo { get; set; }
        public virtual DbSet<Katalog> Katalog { get; set; }
        public virtual DbSet<Notices> Notices { get; set; }
    }
}
