//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOcrApp.appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Katalog
    {
        public int Id { get; set; }
        public string MapNumber { get; set; }
        public string MapTittle { get; set; }
        public string MapScale { get; set; }
        public Nullable<System.DateTime> EditionDate { get; set; }
        public string MapFolio { get; set; }
        public string MapDisk { get; set; }
        public string Comments { get; set; }
    }
}
